[project]
name = "database-as-crime-scene"
version = "0.1.0"
dependencies = [
    "jupysql",
    "sqlalchemy",
    "psycopg2-binary",
    "pandas",
    "python-dotenv",
    "pylint",
    "pydeps",
    "pdoc3",
    "rich",
    "rich-tools",
    "jupyter_contrib_nbextensions",
    "faker",
    "numpy",
    "ruff",
    "black",
    "isort"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
    "ipython"
]

[tool.setuptools.packages.find]
where = ["src"]


[tool.jupysql.SqlMagic]
feedback = true
autopandas = false

[tool.pylint.messages_control]
disable = [
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
    "C0116", # missing-function-docstring
    "R0903", # too-few-public-methods
]