#!/usr/bin/env python3
"""Generate a simple code structure diagram from Python source files."""

import ast
import os
from pathlib import Path


def analyze_file(filepath):
    """Extract classes and functions from a Python file."""
    with open(filepath, 'r') as f:
        try:
            tree = ast.parse(f.read())
        except SyntaxError:
            return None
    
    classes = []
    functions = []
    
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            methods = [m.name for m in node.body if isinstance(m, ast.FunctionDef)]
            classes.append({'name': node.name, 'methods': methods})
        elif isinstance(node, ast.FunctionDef) and node.col_offset == 0:
            # Only top-level functions
            params = [arg.arg for arg in node.args.args]
            functions.append({'name': node.name, 'params': params})
    
    return {'classes': classes, 'functions': functions}


def generate_mermaid(src_dir):
    """Generate Mermaid diagram from source directory."""
    src_path = Path(src_dir)
    
    mermaid = ["classDiagram"]
    
    for py_file in src_path.rglob("*.py"):
        if py_file.name == "__init__.py":
            continue
            
        rel_path = py_file.relative_to(src_path.parent)
        module_name = str(rel_path).replace('/', '.').replace('.py', '')
        
        result = analyze_file(py_file)
        if not result:
            continue
        
        # Add classes
        for cls in result['classes']:
            mermaid.append(f"    class {cls['name']} {{")
            for method in cls['methods']:
                mermaid.append(f"        +{method}()")
            mermaid.append("    }")
        
        # Add functions as a "module" class
        if result['functions']:
            module_class = module_name.replace('.', '_')
            mermaid.append(f"    class {module_class} {{")
            mermaid.append(f"        <<module>>")
            for func in result['functions']:
                params = ', '.join(func['params'])
                mermaid.append(f"        +{func['name']}({params})")
            mermaid.append("    }")
    
    return '\n'.join(mermaid)


if __name__ == "__main__":
    import sys
    
    src_dir = sys.argv[1] if len(sys.argv) > 1 else "src"
    output_file = sys.argv[2] if len(sys.argv) > 2 else "notebooks/autogenerated/code_diagram.mmd"
    
    diagram = generate_mermaid(src_dir)
    
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, 'w') as f:
        f.write(diagram)
    
    print(f"Mermaid diagram generated at {output_file}")
    print("\nYou can:")
    print("1. View it at https://mermaid.live")
    print("2. Use mmdc to convert to PNG: mmdc -i", output_file, "-o notebooks/autogenerated/code_diagram.png")
