name: devbox
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - jupysql
  - psycopg2
  - rich
  - tabulate
  - cowsay
  - ipython-sql
  - python-dotenv 
  - sqlalchemy
  - pandas
  - ipykernel